// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxMipB8wgp3ajI8X06R5qBZbwR22SvlCg',
    appId: '1:157881672459:web:65c6fba3dc9eacd770380e',
    messagingSenderId: '157881672459',
    projectId: 'scrapkart-ai',
    authDomain: 'scrapkart-ai.firebaseapp.com',
    storageBucket: 'scrapkart-ai.firebasestorage.app',
    measurementId: 'G-756FNTKDKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLt79IXUCrNLgMYLl2nc28eORaaE-KKsk',
    appId: '1:157881672459:android:acba1d0a383c9a7070380e',
    messagingSenderId: '157881672459',
    projectId: 'scrapkart-ai',
    storageBucket: 'scrapkart-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTJbSw4Rsg2k-J7eHbew22J_Qtqwuwusc',
    appId: '1:157881672459:ios:d22d4784031d7ac470380e',
    messagingSenderId: '157881672459',
    projectId: 'scrapkart-ai',
    storageBucket: 'scrapkart-ai.firebasestorage.app',
    iosBundleId: 'com.scrapkart.scrapkartAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTJbSw4Rsg2k-J7eHbew22J_Qtqwuwusc',
    appId: '1:157881672459:ios:d22d4784031d7ac470380e',
    messagingSenderId: '157881672459',
    projectId: 'scrapkart-ai',
    storageBucket: 'scrapkart-ai.firebasestorage.app',
    iosBundleId: 'com.scrapkart.scrapkartAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxMipB8wgp3ajI8X06R5qBZbwR22SvlCg',
    appId: '1:157881672459:web:4b29f2c220f5591a70380e',
    messagingSenderId: '157881672459',
    projectId: 'scrapkart-ai',
    authDomain: 'scrapkart-ai.firebaseapp.com',
    storageBucket: 'scrapkart-ai.firebasestorage.app',
    measurementId: 'G-QMQYJTWX87',
  );
}
